[package]
name = "mono-planet-client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
horfimbor-client-derive.workspace = true
horfimbor-client.workspace = true
yew = { version= "0.23", features=["csr", "serde"] }
custom-elements = "0.2"
planet-shared = { path = "../shared" }

horfimbor-time.workspace = true

chrono.workspace = true
gloo-net = "0.7"
reqwasm = "0.5"
weblog = "0.3"
wasm-bindgen = "0.2"
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
rand = "0.10"
gloo-timers = "0.4"


# getrandom is used even by rand in wasm so it's marked as unused
getrandom = { version = "0.4", features = ["wasm_js"] }
uuid = { version = "1.23", features = ["v4"] }

[dependencies.web-sys]
features = [
    "HtmlInputElement",
    "InputEvent",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "ImageData",
]
version = "0.3"

[lints]
workspace = true
